/**
 * Sinh tài liệu CSDL cho hồ sơ nộp bài từ chính Prisma schema (không viết tay, không lệch với code):
 *   - submission/database/erd.mmd           : sơ đồ ERD dạng Mermaid (dán vào mermaid.live để xuất PNG/SVG)
 *   - submission/database/data-dictionary.md: danh sách bảng, cột, kiểu, khóa chính/ngoại, ràng buộc unique
 *   - submission/database/database.sql      : bản sao database.sql (script tạo CSDL cuối cùng)
 *
 * Chạy: node scripts/generate-db-docs.mjs   (cần đã chạy `prisma generate`, ví dụ qua `npm ci`)
 */
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const { Prisma } = require("@prisma/client");

const root = process.cwd();
const outDir = path.join(root, "submission", "database");
mkdirSync(outDir, { recursive: true });

const models = Prisma.dmmf.datamodel.models;
const tableOf = new Map(models.map((m) => [m.name, m.dbName ?? m.name]));

/** Kiểu cột hiển thị: ưu tiên kiểu native của PostgreSQL (vd. Decimal(15,2), Date). */
function columnType(field) {
  if (field.nativeType) {
    const [name, args] = field.nativeType;
    return args?.length ? `${name}(${args.join(",")})` : name;
  }
  return field.kind === "enum" ? `enum ${field.type}` : field.type;
}

/** Khóa ngoại của một model: cột FK → bảng được tham chiếu. */
function foreignKeys(model) {
  const fks = new Map();
  for (const f of model.fields) {
    if (f.kind === "object" && f.relationFromFields?.length) {
      f.relationFromFields.forEach((col, i) => fks.set(col, `${tableOf.get(f.type)}.${f.relationToFields[i]}`));
    }
  }
  return fks;
}

// ---------- ERD (Mermaid) ----------
const erd = ["erDiagram"];
for (const m of models) {
  const fks = foreignKeys(m);
  erd.push(`  ${tableOf.get(m.name)} {`);
  for (const f of m.fields.filter((x) => x.kind !== "object")) {
    const keys = [f.isId && "PK", fks.has(f.name) && "FK", f.isUnique && "UK"].filter(Boolean).join(",");
    erd.push(`    ${columnType(f).split("(")[0].replace(/[^\w]/g, "_")} ${f.name}${keys ? ` ${keys}` : ""}`);
  }
  erd.push("  }");
}
for (const m of models) {
  for (const f of m.fields) {
    if (f.kind !== "object" || !f.relationFromFields?.length) continue;
    // Phía "nhiều" giữ khóa ngoại; cột FK tùy chọn → quan hệ 0..1 từ phía cha.
    const optional = !f.isRequired;
    const back = models.find((x) => x.name === f.type).fields.find((x) => x.relationName === f.relationName && x !== f);
    const many = back?.isList ? "o{" : "o|";
    erd.push(`  ${tableOf.get(f.type)} ${optional ? "|o" : "||"}--${many} ${tableOf.get(m.name)} : "${f.relationFromFields.join(", ")}"`);
  }
}
writeFileSync(path.join(outDir, "erd.mmd"), `${erd.join("\n")}\n`);

// ---------- Data dictionary ----------
const md = [
  "# Data dictionary (generated from prisma/schema.prisma)",
  "",
  "> Generated by `node scripts/generate-db-docs.mjs`. Do not edit by hand — regenerate after schema changes.",
  "> CHECK constraints (amount > 0, type in income/expense, ...) are defined in `database.sql` / the migrations.",
  "",
];
for (const m of models) {
  const fks = foreignKeys(m);
  md.push(`## ${tableOf.get(m.name)}`, "", "| Column | Type | Null | Key | Default |", "| --- | --- | --- | --- | --- |");
  for (const f of m.fields.filter((x) => x.kind !== "object")) {
    const key = [f.isId && "PK", fks.has(f.name) && `FK → ${fks.get(f.name)}`, f.isUnique && "UNIQUE"].filter(Boolean).join(", ");
    const def = f.hasDefaultValue ? (typeof f.default === "object" ? `${f.default.name}()` : String(f.default)) : "";
    md.push(`| ${f.name} | ${columnType(f)} | ${f.isRequired ? "NO" : "YES"} | ${key} | ${def} |`);
  }
  const uniques = m.uniqueFields.filter((u) => u.length > 1);
  if (uniques.length) md.push("", `Composite unique: ${uniques.map((u) => `(${u.join(", ")})`).join("; ")}`);
  md.push("");
}
writeFileSync(path.join(outDir, "data-dictionary.md"), md.join("\n"));

copyFileSync(path.join(root, "database.sql"), path.join(outDir, "database.sql"));
console.log(`Đã sinh ERD + data dictionary cho ${models.length} bảng vào submission/database/`);
